config/routes.rb
Rails.application.routes.draw do
 	
  # get 'gossips/new', to: 'gossips#new' #on affiche le formulaire
  # post 'gossips', to: 'gossips#create' #puis on l'envoie
  resources :gossips

  get 'users/:id', to:'user#show', as: 'users'
  #get 'gossips/:id', to:'gossip#show', as: 'gossips'
  get 'welcome/:user_entry', to: 'welcome#show'
  get '/index', to: 'index#show'
  get 'contact', to: 'contact#show'
  get 'team', to: 'team#show' 
end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :parent, polymorphic: true
	has_many :comments, as: :parent
	has_many :likes
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	validates :title,
		presence: true,
		length: { minimum: 3 }, 
		length: { maximum: 14 }

	validates :content,
		presence: true		

	belongs_to :user
	has_many :join_table_gossip_tags
	has_many :tags, through: :join_table_gossip_tags
	has_many :comments, as: :parent
	has_many :likes
end

app/models/join_table_gossip_tag.rb
class JoinTableGossipTag < ApplicationRecord
	belongs_to :gossip
	belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :gossip, optional: true
	belongs_to :comment, optional: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	belongs_to :sender, class_name: "User"
	belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :join_table_gossip_tags
	has_many :gossips, through: :join_table_gossip_tags

end

app/models/user.rb
class User < ApplicationRecord
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
	has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
	has_many :gossips
	has_many :comments
	belongs_to :city
	has_many :likes
		
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  def show
  	@id = params[:id]
  	@gossip = Gossip.all.find(@id)
  	# @user = User.all.find(@id)
  	
  end


  def new
  	@gossip = Gossip.new
  end



  def create
  	@gossip = Gossip.new(title: params[:title], content: params[:content], user: User.last)
  	
  	# if @gossip.save
  	# 	flash = {success: "Ton gossip est bien enregistré !"}
  	# 	redirect_to index_path
  	# else
  	# 	#flash = {error: "Ton gossip n'a pas été enregistré, recommence..."}
  	# 	render new_gossip_path	
  	# end

  end




end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def show
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def show
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
  	@id = params[:id]
  	@user = User.all.find(@id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/index/show.html.erb
<html>
  <head>
    <title>The Gossip Project</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  </head>
  <body>




	<!-------------------------- NAV BAR -------------------------->




	<nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
		<a class="navbar-brand" <%= link_to 'The Gossip Project', index_path %> </a>

	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    	<span class="navbar-toggler-icon"></span>
	</button>

	<div class="collapse navbar-collapse" id="navbarNav">
		<ul class="navbar-nav">
			<li class="nav-item active">
			<a class="nav-link"<%= link_to 'Accueil', index_path %>  </a>
			</li>
			<li class="nav-item ">
			<a class="nav-link"<%= link_to 'Team', team_path %>  </a>
			</li>
			<li class="nav-item ">
			<a class="nav-link" <%= link_to 'Contact', contact_path %> </a>
			</li>
		</ul>
	</div>

	</nav>




	<!-------------------------- CONTAINER -------------------------->

	<div class="container justify-content-center">

		<div class="row text-center">
			<div class="col-lg-12">
			<br>
			<br>
			<br>
			<br>
			<h1 class="text-center">BIENVENUE DANS GOSSIP NEWS</h1>
			<br/>
		<p>The Hacking Project est une chouette formation, où la communauté est reine. Il se passe plein de choses à Rennes, Paris, Lyon, Montpellier, Bordeaux et c'est dur de connaître tous les gossips. Nous avons donc créé une application où tout le monde peut ajouter des gossips sur ses camarades moussaillons.</p>
		<br/>
		<br/>
		<button class=" btn btn-dark btn-lg active" role="button" aria-pressed="true"><%=link_to 'Nouveau gossip ?', new_gossip_path %> </button>

		<br/>	
		<br/>
		<br/>
		<br/> 

		<!-- Ici, on lui demande d'afficher pour chaque gossip, l'auteur + le contenu -->
		<% Gossip.all.each do |gossip| %>
			<div class="card">
				<div class="card-body">
			  		<h3 class="card-title"><%=link_to gossip.title, gossips_path(gossip.id) %> </h3>
			  		<p class="card-text"><%= gossip.user.first_name %></p>
			      	    	
			    </div>	
	    	</div>
	    <% end %>

			</div>
		</div>

	</div>



	<!-------------------------- SCRIPT -------------------------->

	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>






</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>